name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        working-directory: ./Back-End
        run: npm install

      - name: Rodar os testes
        working-directory: ./Back-End
        run: npm test
        env:
          MONGO_URI: mongodb://mongo:27017/TechChallengeEducaTC_Test
          JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}
          PORT: 3001
