services:
  api:
    build: .
    container_name: lingroom_app
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: lingroom_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
