name: CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

          cache-dependency-path: Back-End/package-lock.json

      - name: Instalar dependências
        working-directory: ./Back-End
        run: npm install

      - name: Rodar os testes
        working-directory: ./Back-End
        run: npm test
        env:
          MONGO_URI: mongodb://localhost:27017/LingroomTC_Test
          JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}
          PORT: 3001
